# name: Docker Image Update CI for GHCR When dotfiles Update

# on:
#   push:
#     branches: [ master ]

# jobs:
#   notify_runner:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger devcontainer runner
#         run: |
#           curl -X POST \
#             -H "Authorization: Bearer ${{ secrets.GH_PAT_INFORM }}" \
#                 -H "Accept: application/vnd.github+json" \
#                 https://api.github.com/repos/cjn4825/Dev-Container/dispatches \
#                 -d '{"event_type":"dotfiles_update_rebuild"}'
